### ISSUE TITLE
Support for lookup tables

### ISSUE THREAD

**Issue by dannyheard7** [SimGus/Chatette#14]
https://blog.rasa.com/improving-entity-extraction/

If this library could take in a lookup file flag that maps to the lookup_tables json entry, it would be really useful

**Comment by SimGus** [comment]
I will look into that. This being said this is not a top priority (and I don't have much time at the moment), so I can't promise you to add support for that soon.

Anyway, thanks for your request :)

**Comment by SimGus** [comment]
Since v1.5.0, you can use the `--base-file` command line option to provide a base file to extend.

If you give it a file containing for example:
```json
{
    "rasa_nlu_data": {
        "lookup_tables": [
            {
                "name": "company",
                "elements": "data/company/startups.csv"
            }
        ],
        "common_examples": null,
        "entity_synonyms": null,
        "regex_features": []
    }
}
```
the generated examples will be added in the `common_examples` (and `entity_synonyms`) fields of such an object. This is described [here](https://github.com/SimGus/Chatette/wiki/Files-organization#base-file).

I don't think I will add a more complete support for lookup tables than that (at least not at the moment).

Sorry for taking so long to look into this, I've been very busy.
