### ISSUE TITLE
Nested slots

### ISSUE THREAD

**Issue by alifanov** [SimGus/Chatette#30]
I haven't found a solution for nesting slots with synonyms
Like
```
@[paymentPeriod:hour]
	hour
	h

@[paymentPeriod:day]
	day
	d

@[paymentPeriod]
	@[paymentPeriod:hour]
        @[paymentPeriod:day]
```
I want to use nested `perymentPeriod` slot like this
```
No,[ per|per?] @[paymentPeriod]
```
But right now I get
```
- No, [[](paymentPeriod)d](paymentPeriod:day)
- No, [[da](paymentPeriod)y](paymentPeriod:day)
- No, [[](paymentPeriod)h](paymentPeriod:hour)
- No, [[hou](paymentPeriod)r](paymentPeriod:hour)
...
```

**Comment by SimGus** [comment]
Hi,

Nesting slots is not a supported feature, because it is not clear what the generated sentence should look like. To me, using the templates you showed, the slot `@[paymentPeriod]` should generate something like this: `[[hour](paymentPeriod:hour)](paymentPeriod)`. As you may know, this is not supported by Rasa.
To avoid having this kind of problems, I will add an error if Chatette detects nested slots in your templates.

Now, seeing your template, I think I understand what you want to be generated: you would like a slot called `paymentPeriod` that could contain either `hour`, `h`, `day` or `d`, is that right?
If so, the following template will achieve this:
```
~[paymentPeriod:hour]
	hour
	h
~[paymentPeriod:day]
	day
	d

@[paymentPeriod]
        ~[paymentPeriod:hour]
        ~[paymentPeriod:day]
```

On the other hand, if you want a slot called `paymentPeriod:hour` that could have the values `hour` or `h` and another one called `paymentPeriod:day` that could have the values `day` or `d`, then I'm afraid you will have to make 2 different slots and use them wherever you want, as in the following template:
```
@[paymentPeriod:hour]
	hour
	h
@[paymentPeriod:day]
	day
	d

~[some alias]
        ... [@[paymentPeriod:hour]|@[paymentPeriod:day]] ...
```

If what you're looking for is some kind of "categories of slots" (e.g. `hour` and `day` being 2 slots that are part of a `paymentPeriod` category), I am afraid Rasa doesn't support this kind of things. Therefore, Chatette doesn't support it neither. That being said, I might add something like this in the far future, but I'll need to find a solution to "translate" them to something Rasa would understand.

Hope this helps!

**Comment by alifanov** [comment]
Right now I use the approach
```
No, @[salary_sum][ per|per?] [@[paymentPeriod:hour]|@[paymentPeriod:day]|@[paymentPeriod:week]|@[paymentPeriod:month]|@[paymentPeriod:year]]
```
to generate
```
- No, [4500.00](salary_sum) per [annum](paymentPeriod:year)
- No, [4500.00](salary_sum) per [d](paymentPeriod:day)
- No, [4500.00](salary_sum) per [day](paymentPeriod:day)
- No, [4500.00](salary_sum) per [h](paymentPeriod:hour)
- No, [4500.00](salary_sum) per [hour](paymentPeriod:hour)
```

but I want to make the template shorter
like
```
No, @[salary_sum][ per|per?] @[paymentPeriod]
```

**Comment by SimGus** [comment]
I  see. Then, I suppose your solution is a good one. To make it easier to reuse your slots, I would suggest using a template such as this:
```
... your slot definitions ...
~[paymentPeriod]
   @[paymentPeriod:day]
   @[paymentPeriod:hour]
   ...
```

You can then use this alias as if it was a slot, rather than needing to write the same list of slots over and over again ;)

For the record, it is also sometimes useful to use variations of slots (but I’m guessing this will not be a solution in your case), like this:
```
@[paymentPeriod#hour]
   hour
   h
@[paymentPeriod#day]
   day
   d
```
You can then use the slot `@[paymentPeriod]` as if it was defined, and the generator will choose one of the variations at random. However, in that case, the name of the generated entity will be `paymentPeriod` and not the name of the chosen variation.

I understand that in your case, none of the solutions I suggested is totally satisfying. I’ll see if I can make some changes that would help in your situation, because I guess such cases must come up often.

Thanks for your questions :)

**Comment by alifanov** [comment]
Thank you
